pipeline{
    agent any
        stages {
            stage('docker build'){
                steps {
                    script{
                        sh "docker build -f Proyecto/IntegracionContinua/Dockerfile -t integracionimage-${BUILD_ID} Proyecto/IntegracionContinua"
                    }
                }
            }
            stage('docker push'){
                steps {
                    script{
                        sh "docker push integracionimage-${BUILD_ID}"
                    }
                }
            }
        }
    }
